my:
  greetings: Hello World from external source
  list:
    values: one,two,three
employee: "{ id: '001', name: 'Binay'}"

db:
  url: http://localhost:3660/external
  username: admin
  password: admin
  driver: db.mysql